# Generated by Django 3.2.7 on 2022-03-28 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='使用者ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='使用者名稱')),
                ('password', models.CharField(max_length=100, verbose_name='使用者密碼')),
                ('hobby', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='使用者興趣')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
